export type Locale = "ar" | "en";

export const EVENT = {
  nameAr: "تشابك",
  nameEn: "TASHABUK",
  datesAr: "٨ - ٩ أكتوبر ٢٠٢٦",
  datesEn: "October 8–9, 2026",
  // Location is TBD — update once confirmed.
  locationAr: "سيتم الإعلان عن الموقع قريبًا",
  locationEn: "Location to be announced",
};

export const dictionaries = {
  ar: {
    dir: "rtl" as const,
    appName: EVENT.nameAr,
    tagline: "حملة توعوية بالاضطرابات العصبية العضلية عند الأطفال",
    description:
      "تشابك حملة توعوية تهدف إلى التعريف بالاضطرابات العصبية العضلية عند الأطفال، ودعم العائلات من خلال المعرفة والتواصل والدعم المجتمعي.",
    eventDates: EVENT.datesAr,
    eventLocation: EVENT.locationAr,
    landing: {
      title: "مكانك بيننا… بس وين قطعتك؟ 🧩",
      subtitle: "باقي خطوة صغيرة عشان تكتمل الصورة…\nحلّ الأحجية وخذ دعوتك الخاصة 💌",
      nameLabel: "اسمك",
      namePlaceholder: "اكتب اسمك الثنائي هنا",
      startButton: "ابدأ التحدي",
      nameRequired: "يرجى كتابة اسمك أولًا",
      leaderboardLink: "لوحة المتصدرين",
    },
    puzzle: {
      title: "رتّب القطع لتكتشف دعوتك",
      instructions: "باقي كم قطعة وتكتمل دعوتك…\nيلا نشوف تقدر تجمع تشابك؟ 🧩",
      timer: "الوقت",
      moves: "عدد المحاولات",
      reset: "إعادة",
      solvedTitle: "أحسنت!",
      solving: "جارٍ الحل...",
    },
    invite: {
      greeting: "أنت مدعو/ة يا",
      lead: "ماذا لو كانت إشارة صغيرة… تحكي الكثير؟",
      bodyLines: [
        "في تشابك نكتشف ما وراء الحركة،",
        "ونقترب أكثر من عالم الاضطرابات العصبية العضلية لدى الأطفال.",
      ],
      closing: "جاهز تتشابك معنا؟",
      dateLabel: "التاريخ",
      locationLabel: "المكان",
      viewLeaderboard: "لوحة المتصدرين",
      playAgain: "العب مرة أخرى",
      yourTime: "وقتك",
      yourRank: "ترتيبك",
      saveImage: "احفظ كصورة",
      savingImage: "جارٍ الحفظ...",
      preparingImage: "لحظات...",
    },
    generalInvite: {
      tapHint: "اضغط لفتح الدعوة",
      pullHint: "اسحب الدعوة للأعلى، أو اضغط الزر",
      pullButton: "أخرج الدعوة",
      title: "أنتم جزء من تشابك",
      lead: "يسعدنا أن تكونوا جزءًا من «تشابك»",
      bodyLines: [
        "حملة توعوية نسلّط فيها الضوء على الاضطرابات العصبية العضلية لدى الأطفال،",
        "ونتشابك معًا لنصنع وعيًا، دعمًا وأملًا.",
      ],
      closing: "وجودكم يكمل الصورة 🧩",
      eventDate: "٩ أكتوبر ٢٠٢٦",
      eventLocation: "سيتم الإعلان عنه قريبًا",
    },
    leaderboard: {
      title: "لوحة المتصدرين",
      subtitle: "أسرع من حل الأحجية وحصل على دعوته",
      rank: "الترتيب",
      name: "الاسم",
      time: "الوقت",
      empty: "لا يوجد لاعبون بعد — كن أول من يحل الأحجية!",
      loading: "جارٍ التحميل...",
      back: "العودة",
    },
    langToggle: "English",
  },
  en: {
    dir: "ltr" as const,
    appName: EVENT.nameEn,
    tagline: "Awareness campaign for neuromuscular disorders in children",
    description:
      "Tashabuk is an awareness campaign shedding light on neuromuscular disorders in children — connecting families through knowledge, support, and community.",
    eventDates: EVENT.datesEn,
    eventLocation: EVENT.locationEn,
    landing: {
      title: "Your place is with us… but where's your piece? 🧩",
      subtitle: "Just one small step to complete the picture…\nsolve the puzzle and get your special invite 💌",
      nameLabel: "Your name",
      namePlaceholder: "Write your first and last name here",
      startButton: "Start the challenge",
      nameRequired: "Please enter your name first",
      leaderboardLink: "Leaderboard",
    },
    puzzle: {
      title: "Piece it together to reveal your invite",
      instructions: "Just a few pieces until your invite is complete…\nLet's see, can you put Tashabuk together? 🧩",
      timer: "Time",
      moves: "Moves",
      reset: "Reset",
      solvedTitle: "Well done!",
      solving: "Solving...",
    },
    invite: {
      greeting: "You're invited,",
      lead: "What if a small sign… says a lot?",
      bodyLines: [
        "At Tashabuk, we discover what lies behind movement,",
        "and come closer to the world of neuromuscular disorders in children.",
      ],
      closing: "Ready to connect with us?",
      dateLabel: "Date",
      locationLabel: "Location",
      viewLeaderboard: "Leaderboard",
      playAgain: "Play again",
      yourTime: "Your time",
      yourRank: "Your rank",
      saveImage: "Save as image",
      savingImage: "Saving...",
      preparingImage: "One sec...",
    },
    generalInvite: {
      tapHint: "Tap to open",
      pullHint: "Slide the invite up, or tap the button",
      pullButton: "Pull out",
      title: "You're part of Tashabuk",
      lead: "We're delighted to have you as part of Tashabuk,",
      bodyLines: [
        "an awareness campaign shining a light on neuromuscular disorders in children,",
        "where we come together to build awareness, support, and hope.",
      ],
      closing: "Your presence completes the picture 🧩",
      eventDate: "October 9, 2026",
      eventLocation: "To be announced soon",
    },
    leaderboard: {
      title: "Leaderboard",
      subtitle: "Fastest solvers get their invite first",
      rank: "Rank",
      name: "Name",
      time: "Time",
      empty: "No players yet — be the first to solve it!",
      loading: "Loading...",
      back: "Back",
    },
    langToggle: "العربية",
  },
} satisfies Record<Locale, unknown>;

export type Dictionary = (typeof dictionaries)[Locale];
